services:
  - type: web
    name: customer-tracking-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    buildFilter:
      paths:
      - "**/*"
    envVars:
      - key: NODE_ENV
        value: production