services:
  - type: web
    name: customer-tracking-app
    runtime: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm run start
    plan: starter
    region: oregon
    env: node
    nodeVersion: 18
    buildFilter:
      paths:
      - "**/*"
    envVars:
      - key: NODE_ENV
        value: production