services:
  - type: web
    name: customer-tracking-phoenix
    env: elixir
    plan: free
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CALENDLY_API_TOKEN
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: MIX_ENV
        value: prod
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PORT
        value: 4000