services:
  - type: web
    name: customer-tracking-app
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    buildFilter:
      paths:
        - "**/*.js"
        - "**/*.ts"
        - "**/*.tsx"
        - "**/*.json"
        - "package.json"
        - "package-lock.json"
        - "client/**"
        - "server/**"
        - "shared/**"
        - "*.config.*"
      ignoredPaths:
        - "**/*.ex"
        - "**/*.exs"
        - "mix.exs"
        - "mix.lock"
        - "_build/**"
        - "deps/**"
        - "priv/**"
        - "**/*.beam"
        - "**/*.erl"
        - "lib/**/*.ex"
        - "config/**/*.ex"
        - "test/**/*.ex"
    envVars:
      - key: NODE_ENV
        value: production