services:
  - type: web
    name: customer-tracking-nodejs
    runtime: node  # 👈 PHẢI có dòng này để Render không hiểu nhầm là Elixir
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    rootDir: .
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CALENDLY_API_TOKEN
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
